### ISSUE TITLE
Integrate into the Metrics project

### ISSUE THREAD

**Issue by ryantenney** [sps/metrics-opentsdb#10]
I'm curious whether you'd be open to integrating metrics-opentsdb as a new module in the Metrics project? Version 4 of the project is focusing on tags and taps (export raw events instead of aggregate metrics), and having an OpenTSDB reporter is going to be a large part of that plan.

**Comment by nsauro** [comment]
+1!

**Comment by sps** [comment]
Hi @ryantenney - not sure how I missed this. This project went into a bit of a blindspot for me.
Are you still interested in integrating this as a module?

In the short term, I've [opened a PR](https://github.com/dropwizard/metrics/pull/993) to add links to this project.

Thanks!
-sean
